/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'auto-approval-rules': AutoApprovalRule;
    'absence-log': AbsenceLog;
    'invoice-pending-review': InvoicePendingReview;
    'invoice-log': InvoiceLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'auto-approval-rules': AutoApprovalRulesSelect<false> | AutoApprovalRulesSelect<true>;
    'absence-log': AbsenceLogSelect<false> | AbsenceLogSelect<true>;
    'invoice-pending-review': InvoicePendingReviewSelect<false> | InvoicePendingReviewSelect<true>;
    'invoice-log': InvoiceLogSelect<false> | InvoiceLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nome visualizzato (valorizzato al primo login Google).
   */
  name?: string | null;
  /**
   * Ruolo operativo. Determina le aree visibili e le azioni permesse.
   */
  role: 'admin' | 'hr' | 'amministrazione';
  /**
   * Stato account. Gli utenti sospesi non possono accedere.
   */
  status: 'invited' | 'active' | 'suspended';
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Regole di auto-approvazione per pseudo manager.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auto-approval-rules".
 */
export interface AutoApprovalRule {
  id: number;
  /**
   * Pseudonimo su Furious (case-sensitive).
   */
  pseudo: string;
  /**
   * Tipo di flusso a cui si applica la regola.
   */
  flowType: 'absence';
  /**
   * Note operative opzionali (non usate dal sistema).
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Log di tutti gli eventi assenza ricevuti da Furious.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "absence-log".
 */
export interface AbsenceLog {
  id: number;
  /**
   * ID assenza su Furious (campo `id` del webhook).
   */
  furiousAbsenceId: number;
  /**
   * Pseudonimo richiedente (campo `pseudo` del webhook).
   */
  pseudo: string;
  /**
   * Data inizio assenza (campo `start_date`).
   */
  startDate: string;
  /**
   * Data fine assenza (campo `end_date`).
   */
  endDate: string;
  /**
   * Tipo assenza (campo `type` — stringa completa da Furious).
   */
  absenceType: string;
  /**
   * Mezza giornata (campo `half_day`: 0=intera, 1=mattina, 2=pomeriggio).
   */
  halfDay?: ('0' | '1' | '2') | null;
  /**
   * Stato del processing. Vedi state machine in 010-collections.md.
   */
  status: 'received' | 'processing' | 'approved' | 'skipped' | 'failed_permanent';
  /**
   * Numero di tentativi di processing eseguiti dal worker.
   */
  attempts?: number | null;
  /**
   * Ultimo messaggio di errore (stringa o JSON serializzato).
   */
  lastError?: string | null;
  /**
   * Timestamp del completamento del processing (approved/skipped/failed).
   */
  processedAt?: string | null;
  /**
   * Payload originale del webhook Furious. Immutabile dopo creazione.
   */
  rawPayload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Nome del task Cloud Tasks accodato (per debug e idempotency).
   */
  taskName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * [R2] Coda fatture in attesa di revisione manuale.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-pending-review".
 */
export interface InvoicePendingReview {
  id: number;
  /**
   * ID fattura su Furious.
   */
  furiousInvoiceId: number;
  /**
   * ID fattura su Starty (da definire in R2).
   */
  startyInvoiceId?: string | null;
  /**
   * Numero PO (campo da chiarire con amministrazione).
   */
  purchaseOrder?: string | null;
  status: 'pending' | 'reviewed' | 'sent' | 'failed_permanent';
  attempts?: number | null;
  lastError?: string | null;
  processedAt?: string | null;
  rawPayload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * [R2] Audit log completo di ogni evento fattura processato.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-log".
 */
export interface InvoiceLog {
  id: number;
  /**
   * ID fattura su Furious.
   */
  furiousInvoiceId: number;
  /**
   * ID fattura su Starty.
   */
  startyInvoiceId?: string | null;
  status: 'received' | 'processing' | 'sent' | 'skipped' | 'failed_permanent';
  attempts?: number | null;
  lastError?: string | null;
  processedAt?: string | null;
  rawPayload:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'auto-approval-rules';
        value: number | AutoApprovalRule;
      } | null)
    | ({
        relationTo: 'absence-log';
        value: number | AbsenceLog;
      } | null)
    | ({
        relationTo: 'invoice-pending-review';
        value: number | InvoicePendingReview;
      } | null)
    | ({
        relationTo: 'invoice-log';
        value: number | InvoiceLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auto-approval-rules_select".
 */
export interface AutoApprovalRulesSelect<T extends boolean = true> {
  pseudo?: T;
  flowType?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "absence-log_select".
 */
export interface AbsenceLogSelect<T extends boolean = true> {
  furiousAbsenceId?: T;
  pseudo?: T;
  startDate?: T;
  endDate?: T;
  absenceType?: T;
  halfDay?: T;
  status?: T;
  attempts?: T;
  lastError?: T;
  processedAt?: T;
  rawPayload?: T;
  taskName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-pending-review_select".
 */
export interface InvoicePendingReviewSelect<T extends boolean = true> {
  furiousInvoiceId?: T;
  startyInvoiceId?: T;
  purchaseOrder?: T;
  status?: T;
  attempts?: T;
  lastError?: T;
  processedAt?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoice-log_select".
 */
export interface InvoiceLogSelect<T extends boolean = true> {
  furiousInvoiceId?: T;
  startyInvoiceId?: T;
  status?: T;
  attempts?: T;
  lastError?: T;
  processedAt?: T;
  rawPayload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}